### PR TITLE
Do not use `Rails.root` if it's nil

### LINKED ISSUE #568: Bullet tries to write log file to /log/bullet.log (i.e. system root, not application root)
When a project that is *not* using Rails, but uses a gem that has [railties](https://github.com/rails/rails/tree/main/railties) as a runtime dependency, trying to have `Bullet` write to `log/bullet.log` will actually try write to `/log/bullet.log` (i.e. instead of writing relative to the project root, it will try to write to the _system_ root).

Found this as our project uses [`Hanami`](https://github.com/hanami/hanami) instead of Rails and [`rswag-specs`](https://github.com/rswag/rswag) (which includes `railties` as a runtime dependency).

Note that this might go unnoticed in some Linux systems, but on latest MacOS systems, the `/` directory is read-only, so it raises a big fat exception:
```
# having `Bullet.bullet_logger = true` on the bullet initializer

⋊> ~/w/o/project on qa ⨯ bundle exec hanami s
Read-only file system @ dir_s_mkdir - /log
/Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:211:in `each'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bullet-6.1.4/lib/bullet.rb:127:in `bullet_logger='
        /Users/Drowze/w/o/project/config/initializers/bullet.rb:4:in `<top (required)>'
        /Users/Drowze/w/o/project/config/environment.rb:10:in `require'
        /Users/Drowze/w/o/project/config/environment.rb:10:in `<top (required)>'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/hanami-1.3.3/lib/hanami/environment.rb:410:in `require'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/hanami-1.3.3/lib/hanami/environment.rb:410:in `require_application_environment'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/hanami-1.3.3/lib/hanami/cli/commands/command.rb:77:in `call'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/hanami-cli-0.3.1/lib/hanami/cli.rb:57:in `call'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/hanami-1.3.3/bin/hanami:6:in `<top (required)>'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/bin/hanami:23:in `load'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/bin/hanami:23:in `<top (required)>'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/bin/bundle:23:in `load'
        /Users/Drowze/.asdf/installs/ruby/2.7.3/bin/bundle:23:in `<main>'
```

This happens because `railties` defines `Rails.root` as nil if `Rails.application` isn't defined. See:
```
# https://github.com/rails/rails/blob/main/railties/lib/rails.rb#L65
def root
  application && application.config.root
end
```

Here on bullet gem, we simply check for `defined?(Rails.root)` to see if we can use it, so essentially we are saying that the  log file path is `#{nil}/log/bullet.log`. A simply patch, suggested on #567, is tweaking that a bit by also checking whether `Rails.root` is different than nil before actually using it.

### PR DESCRIPTION
**Pull request by Drowze**
Fixes #568 by checking if Rails.root is both _defined and different than nil_ before using it.

### CODE REVIEW

File: lib/bullet.rb [hunk 1]
```diff
@@ -71,7 +71,7 @@ def enable?
     end
 
     def app_root
-      @app_root ||= (defined?(::Rails.root) ? Rails.root.to_s : Dir.pwd).to_s
+      @app_root ||= (defined?(::Rails.root) && !::Rails.root.nil? ? Rails.root.to_s : Dir.pwd).to_s
```
Comment (flyerhzm) [inline lib/bullet.rb:74]: `Rails.root` supposed not to be `nil`

Comment (flyerhzm) [reply lib/bullet.rb:74]: oh, I get what you mean after reading issue #568, please add a comment here why `Rails.root` could be `nil` here, thanks.

Comment (Drowze) [reply lib/bullet.rb:75]: Just added, thanks for the feedback!
