### PR TITLE
Mongoid 8.x support add

### LINKED ISSUE #628: Support for mongoid 8.0
Currently getting this exception:

```
➜  tetherx git:(master) ✗ bin/rails c
/opt/homebrew/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bullet'. (Bundler::GemRequireError)
Gem Load Error is: Bullet does not support mongoid 8.0.2 yet
```

### PR DESCRIPTION
**Pull request by randikabanura**
Closes #628

### CODE REVIEW

File: spec/support/mongo_seed.rb [hunk 1]
```diff
@@ -42,6 +42,12 @@ def setup_db
           config.load_configuration(sessions: { default: { database: 'bullet', hosts: %w[localhost:27017] } })
         end
       else
+        if Mongoid::VERSION =~ /\A7.1/ || Mongoid::VERSION =~ /\A8/
```
Comment (randikabanura) [inline spec/support/mongo_seed.rb:45]: https://github.com/mongodb/mongoid/commit/d11c336a625114e73bbdfb57054e54e02fd199c8
